<a href="https://colab.research.google.com/github/durgeshanalyst/JOB_ANALYTICS_LINKEDIN/blob/main/project_job_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install bs4

Collecting bs4Note: you may need to restart the kernel to use updated packages.

  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\user\anaconda3\lib\site-packages (from bs4) (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\user\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.3.1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py): started
  Building wheel for bs4 (setup.py): finished with status 'done'
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1272 sha256=1214b85bbfb06243b2df53b6491ac4eebea8b9ad7961bdad71a86cdcd5a3da26
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\73\2b\cb\099980278a0c9a3e57ff1a89875ec07bfa0b6fcbebb9a8cad3
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1

In [ ]:
from selenium import webdriver
import time
import pandas as pd 
import os
import requests
from bs4 import BeautifulSoup

In [ ]:
from selenium.webdriver.support import select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common import by
from selenium.webdriver.support import expected_conditions as EC

In [ ]:
url1='https://www.linkedin.com/jobs/search/?currentJobId=3258936531&geoId=102713980&location=India'
url2='https://www.linkedin.com/jobs/search/?currentJobId=3259241277&geoId=102713980&location=India&start=50'
url3='https://www.linkedin.com/jobs/search/?currentJobId=3259238016&geoId=102713980&location=India&start=75'
url4='https://www.linkedin.com/jobs/search/?currentJobId=3259208410&geoId=102713980&location=India&start=100'
url5='https://www.linkedin.com/jobs/search/?currentJobId=3259240393&geoId=102713980&location=India&start=125'
url6='https://www.linkedin.com/jobs/search/?currentJobId=3259243179&geoId=102713980&location=India&start=150'
url7='https://www.linkedin.com/jobs/search/?currentJobId=3258908654&geoId=102713980&location=India&start=175'
url8='https://www.linkedin.com/jobs/search/?currentJobId=3258905445&geoId=102713980&location=India&start=200'
url9='https://www.linkedin.com/jobs/search/?currentJobId=3258989297&geoId=102713980&location=India&start=225'
url10='https://www.linkedin.com/jobs/search/?currentJobId=3256982510&geoId=102713980&location=India&start=250'
url11='https://www.linkedin.com/jobs/search/?currentJobId=3258913999&geoId=102713980&location=India&start=275'
url12='https://www.linkedin.com/jobs/search/?currentJobId=3256791749&geoId=102713980&location=India&start=300'
url13='https://www.linkedin.com/jobs/search/?currentJobId=3257843296&geoId=102713980&location=India&start=325'
url14='https://www.linkedin.com/jobs/search/?currentJobId=3258989427&geoId=102713980&location=India&start=350'
url15='https://www.linkedin.com/jobs/search/?currentJobId=3258902499&geoId=102713980&location=India&start=375'
url16='https://www.linkedin.com/jobs/search/?currentJobId=3258296689&geoId=102713980&location=India&start=400'
url17='https://www.linkedin.com/jobs/search/?currentJobId=3259207541&geoId=102713980&location=India&start=425'
url18='https://www.linkedin.com/jobs/search/?currentJobId=3257123545&geoId=102713980&location=India&start=450'
url19='https://www.linkedin.com/jobs/search/?currentJobId=3259241311&geoId=102713980&location=India&start=475'
url20='https://www.linkedin.com/jobs/search/?currentJobId=3258918156&geoId=102713980&location=India&start=500'
url21='https://www.linkedin.com/jobs/search/?currentJobId=3258922426&geoId=102713980&location=India&start=525'
url22='https://www.linkedin.com/jobs/search/?currentJobId=3259540186&geoId=102713980&location=India&start=550'
url23='https://www.linkedin.com/jobs/search/?currentJobId=3258294486&geoId=102713980&location=India&start=575'

url_list=[]

url_list.append(url1)
url_list.append(url2)
url_list.append(url3)
url_list.append(url4)
url_list.append(url5)
url_list.append(url6)
url_list.append(url7)
url_list.append(url8)
url_list.append(url9)
url_list.append(url10)
url_list.append(url11)
url_list.append(url12)
url_list.append(url13)
url_list.append(url14)
url_list.append(url15)
url_list.append(url16)
url_list.append(url17)
url_list.append(url18)
url_list.append(url19)
url_list.append(url20)
url_list.append(url21)
url_list.append(url22)
url_list.append(url23)

len(url_list)

23

In [ ]:
browser=webdriver.Chrome('chromedriver.exe')
browser.get("https://www.linkedin.com")

In [ ]:
username=browser.find_element_by_id("session_key")
username.send_keys("durgeshkumar7b@gmail.com")
password=browser.find_element_by_id("session_password")
password.send_keys("password")

In [ ]:
login_button=browser.find_element_by_class_name("sign-in-form__submit-button")
login_button.click()

In [ ]:
inner_text=[]
href_link_list=[]
soup_list=[]

for i in range(len(url_list)):
    browser.get(url_list[i])
    browser.implicitly_wait(3)
    
    webpage=requests.get(url_list[i]).text
    
    soup_list.append(BeautifulSoup(webpage,'lxml'))
    
    for link in soup_list[i].find_all("a"):
        href_link_list.append(link.get("href"))
        inner_text.append("Inner Text: {}".format(link.text.strip()))

In [ ]:
# for i in range(4,53,2):
#     print(link_list[i],'\n',i)

In [ ]:
href_link_final=[]
for i in range(len(href_link_list)):
    if 'jobs/view' in str(href_link_list[i]):
        href_link_final.append(href_link_list[i])
    else:
        continue

In [ ]:
len(href_link_list),len(href_link_final)

(1506, 575)

In [ ]:
Job_title=[]
Company_name=[]
Location_name=[]
Time_posted=[]
Applicants_count=[]
Job_nature_level=[]
Emp_count_Ctype=[]
Emp_count=[]
Emp_on_Linkedin=[]
Pay_range=[]
Company_followers=[]

In [ ]:
count=0
for link in range(90,len(href_link_final)):
    count+=1
    print(count)
    browser.get(href_link_final[link])
    browser.implicitly_wait(5)
    
    try:
        job_title=browser.find_elements_by_class_name("jobs-unified-top-card__job-title")
        Job_title.append(job_title[0].text)
    except:
        Job_title.append('NA')
    
    try:
        company_name=browser.find_elements_by_class_name("jobs-unified-top-card__company-name")
        Company_name.append(company_name[0].text)
    except:
        Company_name.append('NA')
        
    try:
        location_name=browser.find_elements_by_class_name("jobs-unified-top-card__bullet")
        Location_name.append(location_name[0].text)
    except:
        Location_name.append('NA')
    
    try:
        time_posted=browser.find_elements_by_class_name("jobs-unified-top-card__posted-date")
        Time_posted.append(time_posted[0].text)
    except:
        Time_posted.append('NA')
        
    try:
        applicants_count=browser.find_elements_by_class_name("jobs-unified-top-card__applicant-count")
        Applicants_count.append(applicants_count[0].text)
    except:
        Applicants_count.append('NULL')
        
    try:
        job_nature_level=browser.find_elements_by_class_name("jobs-unified-top-card__job-insight")
        Job_nature_level.append(job_nature_level[0].text)
        Emp_count_Ctype.append(job_nature_level[1].text)
    except:
        Job_nature_level.append('NA')
        Emp_count_Ctype.append('NA')
        
    try:
        emp_count_onLinkedin=browser.find_elements_by_class_name("jobs-company__inline-information")
        Emp_count.append(emp_count_onLinkedin[0].text)
        Emp_on_Linkedin.append(emp_count_onLinkedin[1].text)
        
    except:
        Emp_count.append('NA')
        Emp_on_Linkedin.append('NA')
        
    try:
        pay_range=browser.find_elements_by_class_name("jobs-unified-description__salary-main-rail-card")
        Pay_range.append(pay_range[0].text)
    except:
        Pay_range.append('NA')
        
    try:
        followers=browser.find_elements_by_class_name("artdeco-entity-lockup__subtitle")
        Company_followers.append(followers[0].text)
    except:
        Company_followers.append('NA')

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485

In [ ]:
col=["designation","Company","location","posted_time","Applicant_count","Jobnature_level","Empcount_Ctype","Empcount","Emp_onLinkedin","Payrange","Companyfollowers"]
df=pd.DataFrame({"designation":Job_title,"Company":Company_name,"location":Location_name,"posted_time":Time_posted,"Applicant_count":Applicants_count,"Jobnature_level":Job_nature_level,"Empcount_Ctype":Emp_count_Ctype,"Empcount":Emp_count,"Emp_onLinkedin":Emp_on_Linkedin,"Payrange":Pay_range,"Companyfollowers":Company_followers})

In [ ]:
df.head()

,designation,Company,location,posted_time,Applicant_count,Jobnature_level,Empcount_Ctype,Empcount,Emp_onLinkedin,Payrange,Companyfollowers
0,Chemical Engineer - Trainee/Intern,BASF,"Navi Mumbai, Maharashtra, India",3 hours ago,134 applicants,Internship,"10,001+ employees · Chemical Manufacturing","10,001+ employees","68,070 on LinkedIn",Pay range unavailable\nSalary information is n...,"1,860,642 followers"
1,Associate Planner-3,Target,"Bengaluru, Karnataka, India",13 hours ago,25 applicants,Full-time · Entry level,"10,001+ employees · Retail",NA,NA,,"1,555,863 followers"
2,Supply Manager (Amazon FBA),DigiOrange Inc,India,9 hours ago,NULL,Full-time,11-50 employees,NA,NA,NA,NA
3,Associate,PwC India,"Delhi, Delhi, India",11 hours ago,NULL,Full-time · Entry level,"5,001-10,000 employees · Business Consulting a...",NA,NA,NA,NA
4,Private Banking Executive,Barclays Corporate & Investment Bank,"Bengaluru, Karnataka, India",3 weeks ago,NULL,Full-time · Associate,"10,001+ employees · Financial Services",NA,NA,NA,NA

In [ ]:
print(Location_name)

['Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Gurugram, Haryana, India', 'Gurugram, Haryana, India', 'Noida, Uttar Pradesh, India', 'Noida, Uttar Pradesh, India', 'Gurugram, Haryana, India', 'Bangalore Urban district, Karnataka, India', 'Hyderabad, Telangana, India', 'Gurgaon, Haryana, India', 'Barmer, Rajasthan, India', 'India', 'Kolkata, West Bengal, India', 'Kolkata, West Bengal, India', 'Pune, Maharashtra, India', 'Hyderabad, Telangana, India', 'Mumbai, Maharashtra, India', 'Karnataka, India', 'Delhi, Delhi, India', 'Gurugram, Haryana, India', 'Hyderabad, Telangana, India', 'Mumbai, Maharashtra, India', 'West Bengal, India', 'Uttar Pradesh, India', 'Bangalore Urban, Karnataka, India', 'New Delhi, Delhi, India', 'Pune, Maharashtra, India', 'Hyderabad, Telangana, India', 'Gurugram, Haryana, India', 'Kalyanpur, Bihar, India', 'Noida, Uttar Pradesh, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Imamganj, Bihar, India', 'Imamganj, Bihar, India', 'Imamganj, Bihar, India', 'Imamganj, Bihar, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Imamganj, Bihar, India', 'Kalyanpur, Bihar, India', 'Imamganj, Bihar, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Kalyanpur, Bihar, India', 'Bangalore Urban district, Karnataka, India', 'Bengaluru, Karnataka, India', 'Kolkata, West Bengal, India', 'Mumbai, Maharashtra, India', 'Gurgaon, Haryana, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Gurugram, Haryana, India', 'Gurugram, Haryana, India', 'Bengaluru, Karnataka, India', 'Kalyanpur, Bihar, India', 'Noida, Uttar Pradesh, India', 'Mumbai, Maharashtra, India', 'Kolkata, West Bengal, India', 'Bengaluru, Karnataka, India', 'Delhi, Delhi, India', 'Kalyanpur, Bihar, India', 'Bengaluru, Karnataka, India', 'Kolkata, West Bengal, India', 'Gurugram, Haryana, India', 'Kalyanpur, Bihar, India', 'Mumbai Metropolitan Region', 'Kalyanpur, Bihar, India', 'West Bengal, India', 'Raniganj, Bihar, India', 'Mumbai, Maharashtra, India', 'Gariaband, Chhattisgarh, India', 'Kolkata, West Bengal, India', 'Delhi, Delhi, India', 'Imamganj, Bihar, India', 'Mumbai, Maharashtra, India', 'New Delhi, Delhi, India', 'Kalyanpur, Bihar, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'Hyderabad, Telangana, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'India', 'India', 'Bengaluru, Karnataka, India', 'Pune, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Maharashtra, India', 'India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Chennai, Tamil Nadu, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Chennai, Tamil Nadu, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Chennai, Tamil Nadu, India', 'Chennai, Tamil Nadu, India', 'Chennai, Tamil Nadu, India', 'Chennai, Tamil Nadu, India', 'Hyderabad, Telangana, India', 'Gurugram, Haryana, India', 'Noida, Uttar Pradesh, India', 'Noida, Uttar Pradesh, India', 'Gurugram, Haryana, India', 'Bangalore Urban district, Karnataka, India', 'Hyderabad, Telangana, India', 'Gurgaon, Haryana, India', 'Barmer, Rajasthan, India', 'India', 'Kolkata, West Bengal, India', 'Kolkata, West Bengal, India', 'Pune, Maharashtra, India', 'Hyderabad, Telangana, India', 'Uttar Pradesh, India', 'Mumbai, Maharashtra, India', 'Karnataka, India', 'Delhi, Delhi, India', 'Gurugram, Haryana, India', 'Hyderabad, Telangana, India', 'Mumbai, Maharashtra, India', 'West Bengal, India', 'New Delhi, Delhi, India', 'Bangalore Urban, Karnataka, India', 'Pune, Maharashtra, India', 'Hyderabad, Telangana, India', 'Kalyanpur, Bihar, India', 'Bengaluru, Karnataka, India', 'Gurugram, Haryana, India', 'Kalyanpur, Bihar, India', 'Imamganj, Bihar, India', 'Imamganj, Bihar, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Noida, Uttar Pradesh, India', 'Kolkata, West Bengal, India', 'Mumbai, Maharashtra, India', 'Kalyanpur, Bihar, India', 'Kalyanpur, Bihar, India', 'Bengaluru, Karnataka, India', 'Delhi, Delhi, India', 'Imamganj, Bihar, India', 'Kalyanpur, Bihar, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Kalyanpur, Bihar, India', 'Mumbai Metropolitan Region', 'Raniganj, Bihar, India', 'Mumbai, Maharashtra, India', 'Kolkata, West Bengal, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'Hyderabad, Telangana, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Pune, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Chennai, Tamil Nadu, India', 'Bengaluru, Karnataka, India', 'Bengaluru, Karnataka, India', 'Chennai, Tamil Nadu, India', 'Pune, Maharashtra, India', 'Hyderabad, Telangana, India', 'Kolkata, West Bengal, India', 'India', 'India', 'Chennai, Tamil Nadu, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Chennai, Tamil Nadu, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Pune, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'Navi Mumbai, Maharashtra, India', 'Bengaluru, Karnataka, India', 'India', 'Delhi, Delhi, India', 'Bengaluru, Karnataka, India', 'Gurugram, Haryana, India', 'Bengaluru, Karnataka, India', 'Kalyanpur, Bihar, India', 'Imamganj, Bihar, India', 'Kalyanpur, Bihar, India', 'Noida, Uttar Pradesh, India', 'Kolkata, West Bengal, India', 'Mumbai, Maharashtra, India', 'Kalyanpur, Bihar, India', 'Bengaluru, Karnataka, India', 'Delhi, Delhi, India', 'Kalyanpur, Bihar, India', 'Bengaluru, Karnataka, India', 'Kolkata, West Bengal, India', 'Kalyanpur, Bihar, India', 'Mumbai Metropolitan Region', 'Kalyanpur, Bihar, India', 'Raniganj, Bihar, India', 'Mumbai, Maharashtra, India', 'Kolkata, West Bengal, India', 'Gariaband, Chhattisgarh, India', 'Imamganj, Bihar, India', 'Delhi, Delhi, India', 'Kalyanpur, Bihar, India', 'New Delhi, Delhi, India']

In [ ]:
df.to_csv("jobs.csv")

In [ ]:
browser.get('https://www.linkedin.com/jobs/view/3260970150/?alternateChannel=search&refId=Cs5coxKiKHJWv2NVnjTBAw%3D%3D&trackingId=QgfTeRZBGof%2BLW5ZuELyCg%3D%3D')